module.exports = {
    'port': Number(process.env.PORT || '8080'),
    'database': 'localhost:27017/lottery',
    'lineMinimumValue': 0,
    'lineMaximumValue': 2,
    'lineNumberOfValues': 3,
    'lineDefaultRows': 3,
    'ROUTE_PREFIX': '/api/tickets',
    'LISTENING': 'Listening on port ',
    'NOT_FOUND': 'Not Found',
    'REGEX_VALID_TICKET': '^[0-9a-fA-F]{24}$',
    'MODEL_TICKET': 'Ticket',
    'MODEL_TICKET_ALLLINES': 'allLines',
    'MODEL_LINE': 'Line',
    'MODEL_LINE_ENTRY': 'entry',
    'MODEL_LINE_RESULT': 'result',
    'INFO_TICKET_OPEN': 'Ticket %s being viewed. It can no longer be modified.',
    'ERROR_INVALID_QUANTITY': 'Invalid ticket quantity',
    'ERROR_INVALID_TICKET_ID': 'Invalid ticket id',
    'ERROR_TICKET_CLOSED': 'Cannot modify closed tickets',
};
